[theme]
primaryColor = "#7ee787"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#7ee787"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
